### ISSUE TITLE
Stuck on self-hosted runners

### ISSUE THREAD

**Issue by aqabawe** [lablabs/setup-tflint#1]
<img width="1084" alt="Screenshot 2020-08-25 at 09 57 28" src="https://user-images.githubusercontent.com/830544/91148125-8270f300-e6b9-11ea-8d47-da10b9f4bf79.png">

Is there an argument to always replace it? or to keep the version on the machine?

**Comment by karol-bujacek** [comment]
@aqabawe , no, there is no argument for this.

This action only installs tflint. We expected clean environment and we only extracted downloaded zip (extract zip function from the [actions/tool-cache](https://github.com/actions/toolkit/tree/main/packages/tool-cache) package).

In your environment you have installed it. You probably does not need this action. Or is there anything what I didn’t understand?
